build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
  armv7: ghcr.io/home-assistant/armv7-base-debian:bullseye
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Namer"
  org.opencontainers.image.description: "Namer - Tool for renaming and tagging adult video files with metadata from ThePornDB"
  org.opencontainers.image.source: "https://github.com/brunzbrunz/namer-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
